spring:
  application:
    name: kafka_batch_demo
  kafka:
    bootstrap-servers: localhost:9092
    producer: # for sending test batches
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: ${app.kafka.schema-registry-url}
        auto.register.schemas: true
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: false

app:
  kafka:
    schema-registry-url: http://localhost:8081
    backoff:
      interval: 0
      max-attempts: 0
    inbound:
      transaction-rejected:
        topic: "local.rejected-transactions-service.transaction-rejected"
    outbound:
      transaction-rejected-dlt:
        topic: "local.rejected-transactions-service.transaction-rejected-dlt"
